#$ -S /bin/bash
#$ -N merge_remove-primers_quality-filter
#$ -o /workdir/users/pd378/oil_international/sequence_processing/16S_run1.3/read_process_out.txt
#$ -e  /workdir/users/pd378/oil_international/sequence_processing/16S_run1.3/read_process_err.txt
#$ -wd  /workdir/users/pd378/oil_international/sequence_processing/16S_run1.3/ #Your working directory
#$ -pe parenv 1
#$ -l h_vmem=30G
#$ -t 1-29
#$ -q long.q@cbsubrito.tc.cornell.edu


#export usearch
export PATH=/programs/usearch11.0.667:$PATH
##Set dirs
    WRK=/workdir/users/pd378/oil_international/sequence_processing/16S_run1.3
    OUT=$WRK/s1_merge_qFilter
    mkdir $OUT
    ##Path to the list of file names
    LIST=$WRK/file_lists/master_list.txt
    
####MERGE VARIABLES###
    MERGE_IN=$WRK/rawdata ## raw reads folder
    MERGE_OUT=$OUT/merged_reads ##where to put the merged reads
    MIN_MERGE=283       #cutoff for minimum merge length (15 +/- expected length)
    MAX_MERGE=293       #cutoff for maximum merge length 
    MAX_DIFFS=20       #How many difference are allowed for overlap  (10% of overlap)
    PCTID=85 

####CUTADAPT PRIMER STRIP####  set variables in call
    PSTRIP_OUT=$OUT/primers_stripped #output for the stripped reads

####QUALITY FILTER VARIABLES####
    QFILTER_OUT=$OUT/quality_filtered
    MAX_ERROR=0.1
    
####FILTER UNIQUES VARIABLES####
    UNIQUE_OUT=$WRK/s2_filter_uniques
               
##Make the design file
        DESIGN=$(sed -n "${SGE_TASK_ID}p" $LIST)
        NAME=`basename "$DESIGN"`

##############RUN USEARCH MERGE PAIRS ####################
mkdir $MERGE_OUT
mkdir $MERGE_OUT/stats
FORWARD=$MERGE_IN/${NAME}_R1.fastq
REVERSE=$MERGE_IN/${NAME}_R2.fastq
M_OUT=$MERGE_OUT/${NAME}_merged.fq
M_STATS=$MERGE_OUT/stats/${NAME}.txt

usearch -fastq_mergepairs $FORWARD -reverse $REVERSE -fastq_pctid $PCTID -fastq_minmergelen $MIN_MERGE -fastq_maxmergelen $MAX_MERGE -fastqout $M_OUT -relabel ${NAME}_ 2> $M_STATS

echo $NAME merge complete

############ RUN CUTADAPT PRIMER REMOVAL #####################
mkdir $PSTRIP_OUT
mkdir $PSTRIP_OUT/stats
P_OUT=$PSTRIP_OUT/${NAME}_stripped.fq
P_STATS=$PSTRIP_OUT/stats/${NAME}.txt

cutadapt -a ^YRYRCAGCMGCCGCGGTAATWC...ATTAGAWACCCBDGTAGTCC$ --discard-untrimmed -m 248 -M 252 -o $P_OUT $M_OUT > $P_STATS

echo $NAME primer strip complete

########### RUN QUALITY FILTER ###################
mkdir $QFILTER_OUT
mkdir $QFILTER_OUT/stats
Q_OUT=$QFILTER_OUT/${NAME}_filtered.fa
Q_STATS=$QFILTER_OUT/stats/${NAME}.txt

usearch -fastq_filter $P_OUT -fastq_maxee $MAX_ERROR -fastaout $Q_OUT 2> $Q_STATS

########### RUN FILTER UNIQUES ##################  No longer doing uniques here
mkdir $UNIQUE_OUT
mkdir $UNIQUE_OUT/stats
U_OUT=$UNIQUE_OUT/${NAME}_unique.fa
U_STATS=$UNIQUE_OUT/stats/${NAME}.txt

usearch -fastx_uniques $Q_OUT -fastaout $U_OUT -relabel ${NAME}__uniq_ -sizeout 2> $U_STATS




















